import os
import re
from datetime import datetime
from pathlib import Path

def get_latest_log_entries(log_path, limit=20):
    if not os.path.exists(log_path):
        return []
    with open(log_path, 'r') as f:
        lines = f.readlines()
    return lines[-limit:]

def get_latest_memory_pulses(memory_path, limit=5):
    if not os.path.exists(memory_path):
        return []
    with open(memory_path, 'r') as f:
        content = f.read()
    
    # Using a simpler split if regex is being tricky with escaping
    # Or just use re.split with a more robust pattern
    pulses = content.split('## [')
    pulses = [p.strip() for p in pulses if p.strip()]
    
    formatted_pulses = []
    for p in pulses[-limit:]:
        # Extract the date and the rest
        if ']' in p:
            parts = p.split(']', 1)
            date_str = parts[0].strip()
            body = parts[1].strip().replace('\n', '\n')
            formatted_pulses.append(f"### Pulse: {date_str}\n{body}")
        else:
            formatted_pulses.append(p)
            
    return formatted_pulses

def get_completed_tasks(inbox_path):
    if not os.path.exists(inbox_path):
        return []
    files = list(Path(inbox_path).glob('completed_*.md'))
    completions = []
    for f in files:
        with open(f, 'r') as file:
            content = file.read().splitlines()
            title = content[0].replace('#', '').strip() if content else f.name
            completions.append(f"- {title} (`{f.name}`)")
    return completions

def get_todo_summary(todo_path):
    if not os.path.exists(todo_path):
        return "TODO.md not found."
    with open(todo_path, 'r') as f:
        lines = f.readlines()
    
    todo_items = [line.strip() for line in lines if line.startswith('- [ ]')]
    done_items = [line.strip() for line in lines if line.startswith('- [x]')]
    
    return {
        "todo": todo_items,
        "done_count": len(done_items)
    }

def generate_briefing():
    today = datetime.now().strftime('%Y-%m-%d')
    log_entries = get_latest_log_entries('swarm.log')
    memory_pulses = get_latest_memory_pulses(f'soul/memory/{today}.md')
    completions = get_completed_tasks('inboxes')
    todo_info = get_todo_summary('TODO.md')
    
    log_str = "".join(log_entries)
    pulses_str = "\n".join(memory_pulses)
    completions_str = "\n".join(completions)
    todo_str = "\n".join(todo_info['todo'])
    
    briefing = f"""# Architect Daily Briefing: {today}

## ⚡ System Health & Activity
**Status:** Operational / Active Implementation
**Latest Swarm Logs:**
```
{log_str}
```

## 🧠 Soul Memory (Latest Pulses)
{pulses_str if pulses_str else "No pulses recorded today."} 

## ✅ Recent Completions
{completions_str if completions_str else "No recent completions found in inboxes."} 

## 📋 Outstanding Tasks
{todo_str if todo_str else "No outstanding tasks found."} 
**Total Completed:** {todo_info['done_count']}

---
*Generated by SHAR Engine (Task 027)*
"""
    
    report_name = f"SHAR_BRIEFING_{today.replace('-', '_')}.md"
    with open(report_name, 'w') as f:
        f.write(briefing)
    
    print(f"Briefing generated: {report_name}")
    return report_name

if __name__ == "__main__":
    generate_briefing()
